"""
Schema for workflow generation from natural language.

Defines the structured output format that the Copilot LLM uses
to specify workflow plans for generation.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class AgentPlanTask(BaseModel):
    """A task/agent in the generated workflow plan."""
    id: str                                      # Plan-local ID (e.g. "agent-1")
    name: str                                    # Display name
    description: str                             # What this agent does
    type: str = "builtin"                        # builtin, native, workflow
    system_prompt: Optional[str] = None          # System prompt for the agent
    parent_id: Optional[str] = None              # Parent plan-local ID (null for root)
    routing_strategy: str = "sequential"         # Routing strategy for children
    routing_conditions: Dict[str, str] = Field(default_factory=dict)
    tools: List[str] = Field(default_factory=list)  # Tool names to enable
    model: str = "gpt-4"
    temperature: float = 0.7


class WorkflowPlan(BaseModel):
    """Complete workflow plan generated by Copilot."""
    title: str                                   # Workflow name
    description: str                             # What the workflow does
    agents: List[AgentPlanTask]                  # Agent definitions
    variables: List[Dict[str, Any]] = Field(default_factory=list)  # User input variables
    recommended_entry_prompt: Optional[str] = None  # Suggested first prompt


class PatchOperation(BaseModel):
    """A single patch operation on a workflow."""
    operation: str                               # add, update, delete
    agent_id: Optional[str] = None               # For update/delete
    agent: Optional[AgentPlanTask] = None        # For add/update
    parent_id: Optional[str] = None              # For add (reparenting)


class WorkflowPatch(BaseModel):
    """A set of patch operations for modifying an existing workflow."""
    workflow_id: str
    description: str                             # What changes are being made
    operations: List[PatchOperation]
